// Bundled dataset (generated by scripts/extract.ts). The deployed app never reads the xlsx.
import actions from "@/data/actions.json";
import alternates from "@/data/alternates.json";
import assumptions from "@/data/assumptions.json";
import components from "@/data/components.json";
import concentrationNotes from "@/data/concentration-notes.json";
import entities from "@/data/entities.json";
import events from "@/data/events.json";
import evidence from "@/data/evidence.json";
import indicators from "@/data/indicators.json";
import links from "@/data/links.json";
import nodes from "@/data/nodes.json";
import products from "@/data/products.json";
import scenarios from "@/data/scenarios.json";
import sites from "@/data/sites.json";
import unknowns from "@/data/unknowns.json";
import type { Dataset } from "./types";

export const dataset: Dataset = {
  assumptions: assumptions as Dataset["assumptions"],
  scenarios: scenarios as Dataset["scenarios"],
  products: products as Dataset["products"],
  components: components as Dataset["components"],
  indicators: indicators as Dataset["indicators"],
  entities: entities as Dataset["entities"],
  sites: sites as Dataset["sites"],
  links: links as Dataset["links"],
  evidence: evidence as Dataset["evidence"],
  nodes: nodes as Dataset["nodes"],
  events: events as Dataset["events"],
  alternates: alternates as Dataset["alternates"],
  unknowns: unknowns as Dataset["unknowns"],
  actions: actions as Dataset["actions"],
  concentrationNotes: concentrationNotes.components as Dataset["concentrationNotes"],
  zoneNotes: concentrationNotes.zones as Dataset["zoneNotes"],
};
